from django.contrib import admin
from api.models import *
# Register your models here.
admin.site.register(Company)
admin.site.register(Job)
admin.site.register(License)
admin.site.register(Project)
admin.site.register(ProjectHasJob)
admin.site.register(Role)
admin.site.register(Status)
admin.site.register(Teamproject)
admin.site.register(TeamprojectHasProject)
admin.site.register(TeamprojectHasUser)
admin.site.register(User)
admin.site.register(UserCustomers)
admin.site.register(Usersdetails)
admin.site.register(Priority)
admin.site.register(ProjectDetails)
admin.site.register(JobDetails)
admin.site.register(assets_brand)
admin.site.register(assets_categories)
admin.site.register(assets_storage_unit)
admin.site.register(assets_insurance)
admin.site.register(assets)
admin.site.register(assets_series)
admin.site.register(assets_save_format)
admin.site.register(Platfrom)
admin.site.register(Customers)
admin.site.register(Customers_has_assets)
admin.site.register(Project_Platform_Customers)
admin.site.register(TeamprojectLevel)
admin.site.register(job_has_assets)
admin.site.register(Customers_has_project)
admin.site.register(userrequest)
admin.site.register(requestType)
admin.site.register(requestModule)
admin.site.register(requeststatus)
admin.site.register(request_has_job)