# Generated by Django 3.0.3 on 2020-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_public_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=80, null=True)),
                ('job_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_public_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=80, null=True)),
                ('project_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectHasJob',
            fields=[
                ('project_has_job_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_has_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('scope_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'scope',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamproject',
            fields=[
                ('teamproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('teamproject_public_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('teamproject_name', models.CharField(blank=True, max_length=80, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'teamproject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamprojectHasProject',
            fields=[
                ('teamprojecthasproject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teamproject_has_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamprojectHasUser',
            fields=[
                ('teamprojecthasuser_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teamproject_has_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=80, null=True)),
                ('public_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userclient',
            fields=[
                ('userclient_id', models.AutoField(primary_key=True, serialize=False)),
                ('userclient_public_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('userclient_userkey', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('userclient_exp', models.DateTimeField()),
            ],
            options={
                'db_table': 'userclient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersdetails',
            fields=[
                ('usersdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('usersdetails_firstname', models.CharField(blank=True, max_length=80, null=True)),
                ('usersdetails_lastname', models.CharField(blank=True, max_length=80, null=True)),
                ('usersdetails_phone', models.CharField(blank=True, max_length=80, null=True)),
                ('usersdetails_email', models.CharField(blank=True, max_length=80, null=True)),
                ('usersdetails_position', models.CharField(blank=True, max_length=80, null=True)),
                ('usersdetails_avatar', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'usersdetails',
                'managed': False,
            },
        ),
    ]
