# Generated by Django 3.0.3 on 2020-07-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecthasjob',
            old_name='project_public_id',
            new_name='project_public',
        ),
        migrations.RenameField(
            model_name='projecthasjob',
            old_name='teamproject_public_id',
            new_name='teamproject_public',
        ),
        migrations.RenameField(
            model_name='teamprojecthasproject',
            old_name='project_public_id',
            new_name='project_public',
        ),
        migrations.RenameField(
            model_name='teamprojecthasproject',
            old_name='teamproject_public_id',
            new_name='teamproject_public',
        ),
    ]
