# Generated by Django 3.0.3 on 2020-07-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200718_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthasjob',
            name='job_public_id',
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Priority'),
        ),
        migrations.AddField(
            model_name='projecthasjob',
            name='job_public',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job', to_field='job_public_id'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='projectdetails_desc',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='projectdetails_note',
            field=models.TextField(default=''),
        ),
    ]
