# Generated by Django 3.0.3 on 2020-07-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_projectdetails_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joboperator', to='api.User', to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcreatetor', to='api.User', to_field='public_id'),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('jobdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobdetails_location', models.CharField(blank=True, max_length=80, null=True)),
                ('jobdetails_desc', models.TextField(blank=True, max_length=80, null=True)),
                ('jobdetails_manual', models.CharField(blank=True, max_length=80, null=True)),
                ('jobdetails_note', models.TextField(default='')),
                ('jobdetails_startdate', models.DateField()),
                ('jobdeatils_enddate', models.DateField()),
                ('job_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job', to_field='job_public_id')),
            ],
            options={
                'db_table': 'jobdetails',
            },
        ),
    ]
