# Generated by Django 3.0.6 on 2020-08-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200801_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_has_assets',
            name='assets',
        ),
        migrations.AddField(
            model_name='customers_has_assets',
            name='assets_system_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='job_has_assets',
            fields=[
                ('job_has_assets_id', models.AutoField(primary_key=True, serialize=False)),
                ('assets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assets')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
                ('project_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project', to_field='project_public_id')),
            ],
            options={
                'db_table': 'jobhasassets',
            },
        ),
        migrations.AddField(
            model_name='customers_has_assets',
            name='job_has_assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.job_has_assets'),
        ),
    ]
