# Generated by Django 3.0.6 on 2020-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200803_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
