# Generated by Django 3.0.3 on 2020-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200803_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdetails_location',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
