# Generated by Django 3.0.3 on 2020-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200803_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdetails_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
