# Generated by Django 3.0.3 on 2020-08-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200803_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assets_brand',
            table='assetsbrand',
        ),
    ]
