# Generated by Django 3.0.3 on 2020-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200803_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_has_assets',
            name='assets_is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
