# Generated by Django 3.0.3 on 2020-08-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_job_has_assets_assets_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='jobdeatils_enddate',
            new_name='jobdetails_enddate',
        ),
    ]
