# Generated by Django 3.0.3 on 2020-08-09 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200804_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomers',
            fields=[
                ('usercustomers_id', models.AutoField(primary_key=True, serialize=False)),
                ('usercustomers_public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('usercustomers_userkey', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('usercustomers_passkey', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('usercustomers_exp', models.DateTimeField()),
                ('customers_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Customers', to_field='customers_public_id')),
            ],
            options={
                'db_table': 'usercustomers',
            },
        ),
        migrations.DeleteModel(
            name='Userclient',
        ),
    ]
