# Generated by Django 3.0.3 on 2020-08-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200809_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_has_project',
            fields=[
                ('customershasproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('customers_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Customers', to_field='customers_public_id')),
                ('project_public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project', to_field='project_public_id')),
            ],
            options={
                'db_table': 'customershasproject',
            },
        ),
    ]
