# Generated by Django 3.0.3 on 2020-08-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customers_has_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
    ]
