# Generated by Django 3.0.6 on 2020-08-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200809_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers_has_assets',
            old_name='customers',
            new_name='customers_public',
        ),
    ]
