# Generated by Django 3.0.6 on 2020-08-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200826_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customers_company_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
