# Generated by Django 3.0.3 on 2020-08-26 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customers_customers_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestModule',
            fields=[
                ('requestmodule_id', models.AutoField(primary_key=True, serialize=False)),
                ('requestmodule_details', models.TextField(default='')),
            ],
            options={
                'db_table': 'requestmodule',
            },
        ),
        migrations.CreateModel(
            name='requestType',
            fields=[
                ('requesttype_id', models.AutoField(primary_key=True, serialize=False)),
                ('requesttype_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'requesttype',
            },
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_sn',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='userrequest',
            fields=[
                ('userrequest_id', models.AutoField(primary_key=True, serialize=False)),
                ('userrequest_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('userrequest_type', models.CharField(blank=True, max_length=80, null=True)),
                ('userrequest_details', models.TextField(default='')),
                ('userrequest_created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 15, 22, 58, 293821, tzinfo=utc))),
                ('userrequest_user_details', models.CharField(blank=True, max_length=80, null=True)),
                ('userrequest_phone', models.CharField(blank=True, max_length=80, null=True)),
                ('assets_sn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_requests', to='api.assets', to_field='assets_sn')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
            options={
                'db_table': 'userrequest',
            },
        ),
        migrations.CreateModel(
            name='requeststatus',
            fields=[
                ('requeststatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 15, 22, 58, 294821, tzinfo=utc))),
                ('requestmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestModule')),
                ('userrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userrequest')),
            ],
            options={
                'db_table': 'requeststatus',
            },
        ),
        migrations.AddField(
            model_name='requestmodule',
            name='requesttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestType'),
        ),
    ]
