# Generated by Django 3.0.3 on 2020-08-26 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200826_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 46, 39, 39491)),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Status'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='userrequest_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 26, 22, 46, 39, 38491)),
        ),
        migrations.CreateModel(
            name='request_has_job',
            fields=[
                ('requesthasjob_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Job', to_field='job_public_id')),
                ('userrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userrequest')),
            ],
            options={
                'db_table': 'requesthasjob',
            },
        ),
    ]
